#server:
#  port: 8888
#  spring:
#   profiles:
#   active: prod
#   激活环境
#---
#server:
# port: 8883
#spring:
# profiles: dev
#---
#server
# port: 8883
# spring:
#  profiles:  prod
#---
spring:
  jackson:
    default-property-inclusion: non_null
#/// 驼峰命名
    mybatis:
      configuration:
        map-underscore-to-camel-case: true

#引入vue
  spring:
   thymeleaf:
   prefix: classpath:/static/
